apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-processing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata-processing-service
  template:
    metadata:
      labels:
        app: metadata-processing-service
    spec:
      containers:
        - name: metadata-processing-service
          image: metadata-processing-service:latest
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/metadata"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
