apiVersion: v1
kind: Service
metadata:
  name: metadata-processing-service
spec:
  selector:
    app: metadata-processing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: LoadBalancer
